### ISSUE TITLE
Learned alchemy recipes are still showing up on missing tradeskills list

### ISSUE THREAD

**Issue by zune127** [Thumbkin/MissingTradeSkillsList_TBC#11]
Alchemy recipes are not updated when you learn them as before. Learned multiple potion from TBC and classic era, they are still popping up in the missing tradeskills list.

Tested with and without other addons, did scripterrors 1 and no errors presented itself. Was on the correct character for alchemy recipes.

**Comment by Thumbkin** [comment]
Have you always opened the Alchemy Profession window itself?
The addon needs the Blizzard Profession window before it can scan/update the known recipes/skill of a character.
I can not call the API directly to do this.

**Comment by Gamerslove** [comment]
I'm having the same exact issue but with enchanting tbc formulas. The ones that can be bought from a trainer or vendor are not registering as learned. Using the latest version.

**Comment by Thumbkin** [comment]
Can you try again with the latest (v2.5.08)? I changed the scanning method

**Comment by Gamerslove** [comment]
> Can you try again with the latest (v2.5.08)? I changed the scanning method

That worked, thanks! <3

**Comment by Thumbkin** [comment]
Closing this for now then
