### ISSUE TITLE
quest.lua:31: attempt to index local 'npc' (a nil value)

### ISSUE THREAD

**Issue by rbpaiett** [Thumbkin/MissingTradeSkillsList_TBC#12]
This happens after I open any tradeskill and then close it.  After that it happens every time I open it and when I close it:

5x ...ceMissingTradeSkillsList_TBC\logic\quest.lua:31: attempt to index local 'npc' (a nil value)
[string "@MissingTradeSkillsList_TBC\logic\quest.lua"]:31: in function `GetQuestByIds'
[string "@MissingTradeSkillsList_TBC\ui\common\skill_detail_frame.lua"]:619: in function `ShowDetailsOfSkillTypeQuest'
[string "@MissingTradeSkillsList_TBC\ui\common\skill_detail_frame.lua"]:773: in function `ShowDetailsOfSkillTypeItem'
[string "@MissingTradeSkillsList_TBC\ui\common\skill_detail_frame.lua"]:405: in function `ShowDetailsOfSkill'
[string "@MissingTradeSkillsList_TBC\ui\common\list_frame.lua"]:204: in function `HandleSelectedListItem'
[string "@MissingTradeSkillsList_TBC\ui\common\list_frame.lua"]:384: in function `RefreshList'
[string "@MissingTradeSkillsList_TBC\ui\common\list_frame.lua"]:371: in function `ChangeFilters'
[string "@MissingTradeSkillsList_TBC\ui\common\filter_frame.lua"]:196: in function `ResetFilters'
[string "@MissingTradeSkillsList_TBC\ui\common\base_frame.lua"]:41: in function `ResetFilters'
[string "@MissingTradeSkillsList_TBC\ui\mainframes\missing_tradeskills_frame.lua"]:23: in function `Hide'
[string "@MissingTradeSkillsList_TBC\ui\event_handler.lua"]:163: in function `?'
[string "@MissingTradeSkillsList_TBC\ui\event_handler.lua"]:319: in function <...dOns\MissingTradeSkillsList_TBC\ui\event_handler.lua:316>
[string "=[C]"]: in function `closeFunc'
[string "@Armory\Frames\ArmoryTradeSkillFrame.lua"]:906: in function <...rfaceArmory\Frames\ArmoryTradeSkillFrame.lua:895>
[string "@Armory\Frames\ArmoryTradeSkillFrame.lua"]:919: in function `CloseTradeSkill'
[string "@Skillet-Classic\UI\MainFrame.lua"]:2596: in function `SkilletFrameForceClose'
[string "@Skillet-Classic\UI\MainFrame.lua"]:2616: in function <Skillet-Classic\UI\MainFrame.lua:2614>
[string "=[C]"]: in function `securecall'
[string "@FrameXML\UIParent.lua"]:2765: in function `CloseWindows'
[string "@FrameXML\UIParent.lua"]:2790: in function <FrameXML\UIParent.lua:2780>
[string "=[C]"]: in function `securecall'
[string "@FrameXML\UIParent.lua"]:3426: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
self = <table> {
 GetQuestById = <function> defined @MissingTradeSkillsList_TBC\logic\quest.lua:57
 GetQuestByIds = <function> defined @MissingTradeSkillsList_TBC\logic\quest.lua:13
 GetQuestsByIds = <function> defined @MissingTradeSkillsList_TBC\logic\quest.lua:68
}
ids = <table> {
 1 = 769
}
i = 1
quest = <table> {
 min_xp_level = 4
 expansion = 1
 name = <table> {
 }
 npcs = <table> {
 }
 id = 769
 phase = 1
}
npcs = <table> {
}
npc = nil
(*temporary) = <table> {
}
(*temporary) = "name"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
}
(*temporary) = <function> defined @MissingTradeSkillsList_TBC\logic\tools.lua:451
(*temporary) = "name"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'npc' (a nil value)"

**Comment by Thumbkin** [comment]
This is fixed in the next version, if you want the fix for now:

open file ./logic/quest.lua and change the part of

                            -- only 1 NPC possible
                            local npc = npcs[1]
                            -- check if we are able to interact with npc
                            if not npc then
to

                            -- only 1 NPC possible
                            local npc = npcs[1]
                            -- check if we are able to interact with npc
                            if npc then

**Comment by rbpaiett** [comment]
Thank you very much!
