### ISSUE TITLE
Old Classic Spanish translations being used instead of new TBC ones

### ISSUE THREAD

**Issue by coneone** [Thumbkin/MissingTradeSkillsList_TBC#2]
Hi!

The current version (2.5.1) is using old Classic spanish translations for already existent items/skills.

Just as a simple example, the first Mining skill Smelt Copper is translated as `Cobre fundido` in the addon, but the actual string in game is `Fundir cobre`.
This is the wowhead link for reference: https://es.tbc.wowhead.com/spell=2657/fundir-cobre

TBC brought a big rehaul of the otherwise clumsy spanish translation.

**Comment by Thumbkin** [comment]
Thanks for the heads up.
However a full update on translation for "old" skills will only be done once all current data has been added.
The new TBC data however will already have the good/new translations

**Comment by Thumbkin** [comment]
Should be fixed in v2.5.2
