### ISSUE TITLE
Getting LUA errors as soon as I log in to the game with addon enabled.

### ISSUE THREAD

**Issue by Jovzin** [Thumbkin/MissingTradeSkillsList_TBC#7]
Hello team,
I updated to the latest version of your addon and as soon as I log in to the game I am getting like below errors: 

Message: ...ns\MissingTradeSkillsList_TBC\ui\saved_variables.lua:496: attempt to index global 'MTSLUI_PLAYER' (a nil value)
Time: Mon May 31 09:26:20 2021
Count: 1
Stack: ...ns\MissingTradeSkillsList_TBC\ui\saved_variables.lua:496: attempt to index global 'MTSLUI_PLAYER' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\MissingTradeSkillsList_TBC\ui\saved_variables.lua"]:496: in function `GetShowWelcomeMessage'
[string "@Interface\AddOns\MissingTradeSkillsList_TBC\logic\player_npc.lua"]:64: in function `LoadPlayer'
[string "@Interface\AddOns\MissingTradeSkillsList_TBC\ui\event_handler.lua"]:19: in function `?'
[string "@Interface\AddOns\MissingTradeSkillsList_TBC\ui\event_handler.lua"]:302: in function <...dOns\MissingTradeSkillsList_TBC\ui\event_handler.lua:299>

Locals: 

Message: ...ns\MissingTradeSkillsList_TBC\ui\saved_variables.lua:634: attempt to index global 'MTSLUI_PLAYER' (a nil value)
Time: Mon May 31 09:26:45 2021
Count: 2
Stack: ...ns\MissingTradeSkillsList_TBC\ui\saved_variables.lua:634: attempt to index global 'MTSLUI_PLAYER' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\MissingTradeSkillsList_TBC\ui\saved_variables.lua"]:634: in function `GetEnhancedTooltipActive'
[string "@Interface\AddOns\MissingTradeSkillsList_TBC\ui\tooltip.lua"]:22: in function <...ace\AddOns\MissingTradeSkillsList_TBC\ui\tooltip.lua:20>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetInventoryItem'
[string "@Interface\FrameXML\PaperDollFrame.lua"]:1516: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: 

Message: ...ns\MissingTradeSkillsList_TBC\ui\saved_variables.lua:634: attempt to index global 'MTSLUI_PLAYER' (a nil value)
Time: Mon May 31 09:27:11 2021
Count: 4
Stack: ...ns\MissingTradeSkillsList_TBC\ui\saved_variables.lua:634: attempt to index global 'MTSLUI_PLAYER' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\MissingTradeSkillsList_TBC\ui\saved_variables.lua"]:634: in function `GetEnhancedTooltipActive'
[string "@Interface\AddOns\MissingTradeSkillsList_TBC\ui\tooltip.lua"]:22: in function <...ace\AddOns\MissingTradeSkillsList_TBC\ui\tooltip.lua:20>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetQuestLogItem'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>

Locals:

**Comment by Thumbkin** [comment]
Should be fixed in release 2.5.3
